#ifdef VMC_SUPPORTED_AMPLITUDE_TYPE
VMC_SUPPORTED_AMPLITUDE_TYPE(amplitude_t);
VMC_SUPPORTED_AMPLITUDE_TYPE(real_t);
#endif

#ifdef VMC_SUPPORTED_REAL_TYPE
VMC_SUPPORTED_REAL_TYPE(real_t);
#endif

#ifdef VMC_SUPPORTED_TYPES_PLUGIN
#include VMC_SUPPORTED_TYPES_PLUGIN
#endif
